CREATE TABLE "currencies" (
	"id" text PRIMARY KEY NOT NULL,
	"name" text,
	"ticker" text,
	"rate" real DEFAULT 1,
	"buy_margin_max" real DEFAULT 1,
	"sell_margin_max" real DEFAULT 1,
	"sell_margin_min" real,
	"tradeable" boolean,
	"update_at" timestamp,
	"sign" text,
	"photo" text,
	"created_at" timestamp NOT NULL,
	"updated_at" timestamp NOT NULL,
	"buy_margin_min" real,
	"type_of" text,
	"float_display_order" integer DEFAULT 0 NOT NULL,
	"fx_reserve_pool" real DEFAULT 0 NOT NULL,
	"fx_reserve_weight" real DEFAULT 0 NOT NULL,
	"icon" text,
	"sell_margin_target" numeric DEFAULT '0.0',
	"buy_margin_target" numeric DEFAULT '0.0',
	"display_weight_web" numeric DEFAULT '0.0',
	"display_weight_float" numeric DEFAULT '0.0',
	"source" text,
	"float_threshold_bottom" real DEFAULT 0,
	"float_threshold_top" real DEFAULT 0,
	"fx_reserve_hardcost_pool" real DEFAULT 0,
	"sell_margin_atm" real,
	"buy_margin_atm" real,
	"hex_color" text DEFAULT '#D3D3D3',
	"spread" real DEFAULT 1,
	"offset" real DEFAULT 1,
	"we_buy" real DEFAULT 1,
	"we_sell" real DEFAULT 1,
	"float_target_percent" real DEFAULT 0,
	"float_target_in_cad" real DEFAULT 0,
	"float_threshold_elasticity" real DEFAULT 0.01,
	"organization_id" bigint,
	"rate_decimal_places" integer DEFAULT 2,
	"amount_decimal_places" integer DEFAULT 2,
	"offset_premium" real DEFAULT 0,
	"rate_api" text DEFAULT '',
	"api" integer DEFAULT 0,
	"network" text,
	"chain_id" text,
	"symbol" text,
	"contract" text,
	"underlying" text,
	"rate_api_identifier" text NOT NULL,
	"rate_updated_at" timestamp NOT NULL,
	"advertisable" boolean DEFAULT true NOT NULL,
	"buy_advertisable" boolean DEFAULT true,
	"sell_advertisable" boolean DEFAULT true,
	CONSTRAINT "index_currencies_on_name" UNIQUE("name"),
	CONSTRAINT "index_currencies_on_ticker" UNIQUE("ticker")
);
--> statement-breakpoint
ALTER TABLE "denominations" ALTER COLUMN "currency_id" SET DATA TYPE text;--> statement-breakpoint
CREATE INDEX "index_currencies_on_branch_id" ON "currencies" USING btree ("organization_id");--> statement-breakpoint
CREATE INDEX "index_currencies_on_typeof" ON "currencies" USING btree ("type_of");--> statement-breakpoint
ALTER TABLE "denominations" ADD CONSTRAINT "denominations_currency_id_currencies_id_fk" FOREIGN KEY ("currency_id") REFERENCES "public"."currencies"("id") ON DELETE no action ON UPDATE no action;